version: '2'
services:
  hipstertest01-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/hipsterTest01/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hipsterTest01
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
